# Generated by Django 6.0.6 on 2026-06-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('available', models.BooleanField(default=True)),
                ('truck_capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Load',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('pickup', models.CharField(max_length=200)),
                ('delivery', models.CharField(max_length=200)),
                ('weight', models.IntegerField()),
                ('status', models.CharField(default='Available', max_length=50)),
            ],
        ),
    ]
