# Generated by Django 6.0.6 on 2026-06-24 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truck'),
        ),
    ]
