# Generated by Django 6.0.6 on 2026-06-24 02:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0003_driver_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='driver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.driver'),
        ),
    ]
