# Generated by Django 6.0.6 on 2026-06-24 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0004_load_driver'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trailer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trailer_number', models.CharField(max_length=50)),
                ('loaded', models.BooleanField(default=False)),
                ('location', models.CharField(max_length=200)),
            ],
        ),
    ]
