# Generated by Django 6.0.6 on 2026-06-24 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0005_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='trailer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.trailer'),
        ),
    ]
