# Generated by Django 6.0.6 on 2026-07-05 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0007_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='hours_remaining',
            field=models.IntegerField(default=11),
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='driver',
            name='status',
            field=models.CharField(default='Available', max_length=20),
        ),
    ]
