# Generated by Django 6.0.6 on 2026-07-05 22:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0008_driver_hours_remaining_driver_phone_driver_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='truck',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.truck'),
        ),
    ]
