# Generated by Django 6.0.6 on 2026-07-08 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0009_load_truck'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='ai_score',
            field=models.IntegerField(default=0),
        ),
    ]
