# Generated by Django 6.0.6 on 2026-07-15 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0010_driver_ai_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='fuel_efficiency',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='loads_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='driver',
            name='miles_today',
            field=models.IntegerField(default=0),
        ),
    ]
