# Generated by Django 6.0.6 on 2026-07-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0012_load_distance_load_driver_pay_load_fuel_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='loaded',
        ),
        migrations.AddField(
            model_name='trailer',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='capacity',
            field=models.IntegerField(default=53000),
        ),
        migrations.AddField(
            model_name='trailer',
            name='current_load',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trailers', to='fleet.load'),
        ),
        migrations.AddField(
            model_name='trailer',
            name='last_inspection',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trailer',
            name='status',
            field=models.CharField(choices=[('Empty', 'Empty'), ('Loaded', 'Loaded'), ('Maintenance', 'Maintenance'), ('Out of Service', 'Out of Service')], default='Empty', max_length=20),
        ),
        migrations.AddField(
            model_name='trailer',
            name='utilization',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='trailer_number',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
