# Generated by Django 6.0.6 on 2026-07-20 01:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0013_remove_trailer_loaded_trailer_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trailer',
            name='current_load',
        ),
    ]
