# Generated by Django 6.0.6 on 2026-07-20 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0020_load_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='trailer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trailers', to='fleet.company'),
        ),
        migrations.AlterField(
            model_name='truck',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trucks', to='fleet.company'),
        ),
    ]
