# Generated by Django 6.0.6 on 2026-07-24 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0021_trailer_company_alter_truck_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='latitude',
            field=models.FloatField(default=39.7684),
        ),
        migrations.AddField(
            model_name='truck',
            name='longitude',
            field=models.FloatField(default=-86.1581),
        ),
    ]
