# Generated by Django 6.0.6 on 2026-08-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0022_truck_latitude_truck_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='shift_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='equipment_type',
            field=models.CharField(default='Dry Van', max_length=50),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='priority',
            field=models.CharField(default='Normal', max_length=20),
        ),
    ]
