# Generated by Django 6.0.6 on 2026-08-02 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0023_driver_shift_start_load_delivery_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='miles',
            field=models.IntegerField(default=0),
        ),
    ]
