# Generated by Django 6.0.6 on 2026-08-08 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0024_load_miles'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='home_terminal',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='driver',
            name='shift_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='fuel_efficiency',
            field=models.FloatField(default=7.0),
        ),
        migrations.AlterField(
            model_name='driver',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Driving', 'Driving'), ('Off Duty', 'Off Duty'), ('On Break', 'On Break')], default='Available', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='truck_capacity',
            field=models.IntegerField(default=53000),
        ),
        migrations.AlterField(
            model_name='load',
            name='priority',
            field=models.CharField(choices=[('Low', 'Low'), ('Normal', 'Normal'), ('High', 'High'), ('Critical', 'Critical')], default='Normal', max_length=20),
        ),
        migrations.AlterField(
            model_name='load',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='trailer',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='truck',
            name='capacity',
            field=models.IntegerField(default=40000),
        ),
    ]
