# Generated by Django 6.0.6 on 2026-08-16 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0025_driver_home_terminal_driver_shift_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='latitude',
            field=models.FloatField(default=39.7684),
        ),
        migrations.AddField(
            model_name='driver',
            name='longitude',
            field=models.FloatField(default=-86.1581),
        ),
    ]
