# Generated by Django 6.0.6 on 2026-08-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0026_driver_latitude_driver_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='pickup_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='pickup_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
