# Generated by Django 6.0.6 on 2026-08-17 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0027_load_pickup_latitude_load_pickup_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='load',
            name='delivery_latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='load',
            name='delivery_longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
